### ISSUE TITLE
Client error is showing after clicking grant new access token

### ISSUE THREAD

**Issue by tvigneshnayak** [vdespa/Postman_Dropbox_API_Auth2.0#1]
Hi Valentin, I was following your tutorial "OAuth 2.0 Authorization Flow using the Dropbox API and Postman" on YouTube.
(https://youtu.be/YpmEkNJubHA?feature=shared). I am facing some issue after clicking grant new access token.

Steps followed: 1. Configured the app in Dropbox and provided relevant information in settings and permission.
2. Go to postman and save the app key and app secret in environment variables.
3.  Create a new request and go to authorization.
4. Select Oauth2 as type and fill the relevant details.

Chrome version: Version 116.0.5845.111 (Official Build) (64-bit)
Postman version: 10.17.4-230825-0809
Drop Box : Using on web(not able to find the version)

Observation : There is no authorize using browser option in postman and callback URL is not matching with the URL you provided. After clicking on grant new access token it is showing below error: 
More details for developers
Invalid redirect_uri: "https://oauth.pstmn.io/v1/browser-callback": It must exactly match one of the redirect URIs you've pre-configured for your app (including the path).

![postman](https://github.com/vdespa/Postman_Dropbox_API_Auth2.0/assets/104362007/7489f295-5f47-46f4-8917-7af2962c749b)
![postman2](https://github.com/vdespa/Postman_Dropbox_API_Auth2.0/assets/104362007/01ee2b77-5c98-4f1e-90dc-616262f965ba)

**Comment by vdespa** [comment]
Did you configure https://oauth.pstmn.io/v1/browser-callback in Dropbox as an allowed URI?

**Comment by tvigneshnayak** [comment]
Thanks a lot it worked. I am able to generate tokens now:)
![postman3](https://github.com/vdespa/Postman_Dropbox_API_Auth2.0/assets/104362007/90f8d91d-8c39-4429-ae57-5ff0912b58ad)
